name: Bun CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: tests
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1.1.1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run test
        env:
          MONGO_URI: mongodb://root:password@mongo:27017/tests
          JWT_SECRET: jwt_secret_token
